name: SNIPER
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: final-userbot
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: تحميل الاصدار
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: تهيئة Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: رفع/اضافة التشغيل السابق
        run: |
          echo "📥 جاري تحميل البيانات من فرع التخزين..."
          if git fetch origin bot-data-storage 2>/dev/null; then
            echo "✅ تم العثور على فرع التخزين"
            git checkout origin/bot-data-storage -- . 2>/dev/null || echo "⚠️ لا توجد بيانات سابقة"
            echo "✅ تم استبدال الملفات القديمة بنسخة التخزين"
          else
            echo "⚠️ لا يوجد فرع تخزين، سيبدأ السورس ببيانات جديدة"
          fi
          echo "📂 التحقق من الملفات بعد التحميل:"
          ls -la *.db *.json *.session *.txt *.png *.jpg *.jpeg 2>/dev/null || true
          if ! ls *.session *.db 1> /dev/null 2>&1; then
            echo "❌ تحذير: ماكو ملفات بيانات (session/db) انوجدت!"
          else
            echo "✅ الملفات الأساسية موجودة بعد الاستبدال"
          fi

      - name: تحميل المتطلبات
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: متطلبات الميوزك
        run: |          
          sudo apt-get install -y ffmpeg
                              
      - name: بدء السورس
        run: python jj.py

      - name: حفظ بيانات هذا التشغيل
        if: always()
        run: |
          git checkout main
          git checkout bot-data-storage 2>/dev/null || git checkout -b bot-data-storage
          echo "jj.py" >> .gitignore
          git add --all
          git commit -m "🤖 Auto-update bot data - $(date +'%Y-%m-%d %H:%M:%S')" || echo "ℹ️ لا توجد تغييرات للحفظ"
          git push origin bot-data-storage --force || echo "❌ فشل رفع البيانات"
          git checkout main

      - name: تاكيد العمليات
        run: |
          echo "✅ العملية انتهت بنجاح"
          echo "📦 البيانات محفوظة في فرع: bot-data-storage"
